// pages/document/[id].tsx
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Card, CardContent, Typography, TextField, Button, Grid } from '@mui/material';

import { Document } from '@/lib/types';

export default function DocumentPage() {
  const router = useRouter();
  const { id } = router.query; // Get document ID from the URL
  const [document, setDocument] = useState<Document | null>(null);
  const [comment, setComment] = useState('');

  // Mock fetch function to get a document by ID
  const fetchDocument = async () => {
    const fetchedDoc: Document = {
      id: '1',
      title: 'Business Process',
      type: 'business-process',
      content: 'This is a detailed business process document generated by AI.',
    };
    setDocument(fetchedDoc);
  };

  useEffect(() => {
    if (id) {
      fetchDocument();
    }
  }, [id]);

  if (!document) {
    return <div>Loading...</div>;
  }

  const handleCommentSubmit = () => {
    // Handle comment submission logic (e.g., save comment to DB)
    console.log('Comment submitted:', comment);
    setComment('');
  };

  return (
    <>
    <Card>
        <CardContent>
          <Typography variant="h5">{document.title}</Typography>
          <Typography variant="subtitle1" gutterBottom>
            Type: {document.type}
          </Typography>
          <Typography variant="body1" gutterBottom>
            {document.content}
          </Typography>
        </CardContent>
      </Card>

      {/* Comment Section */}
      <Grid container spacing={2} sx={{ marginTop: 2 }}>
        <Grid item xs={12}>
          <Typography variant="h6">Add a Comment</Typography>
          <TextField
            value={comment}
            onChange={(e) => setComment(e.target.value)}
            fullWidth
            multiline
            rows={4}
            placeholder="Write your comment here..."
            variant="outlined"
          />
          <Button
            variant="contained"
            color="primary"
            sx={{ marginTop: 2 }}
            onClick={handleCommentSubmit}
          >
            Submit Comment
          </Button>
        </Grid>
      </Grid>
    
    </>
    
      
    
  );
}
